# This file is generated by nix-repin. Do not edit.

{ fetchFromGitHub }:

let
  date = "2026-08-11";
  rev = "eb92bfe4adc24c99e0ba7a31d432e5429efa9366";
  src = fetchFromGitHub {
    owner = "so1ve";
    repo = "xwayland-satellite";
    inherit rev;
    hash = "sha256-S8NLPaw754IO6heLzY4cNjW2GXY76E9TZW3glSOKDTM=";
  };
in
{
  inherit date rev src;
}
