# This file is generated by nix-repin. Do not edit.

{ fetchFromGitHub }:

let
  date = "2026-08-12";
  rev = "9ab2fc97d8cb628bb77488d781fa0f3f827a1476";
  src = fetchFromGitHub {
    owner = "so1ve";
    repo = "niri";
    inherit rev;
    hash = "sha256-637Qf4k/sfwBBc6TmSaAnVGCSaBIlDeaIZi4ezHIfNg=";
  };
in
{
  inherit date rev src;
}
