# This file is generated by nix-repin. Do not edit.

{ fetchFromGitHub }:

let
  version = "4.4.1";
  rev = "v4.4.1";
  src = fetchFromGitHub {
    owner = "BIT-Admin";
    repo = "Yanhekt-AutoSlides";
    inherit rev;
    hash = "sha256-Db6djIaTupYKFzZ+alpsjaGxoqJbmULL5uedxqNq1pI=";
  };
in
{
  inherit version rev src;
}
