# This file is generated by nix-repin. Do not edit.

{ fetchFromGitHub }:

let
  date = "2026-08-05";
  rev = "8cff1ac3e7b35fe41235856ab98800b2281cac57";
  src = fetchFromGitHub {
    owner = "TibixDev";
    repo = "winboat";
    inherit rev;
    hash = "sha256-8Q4INSbmuNZxqTLLK2HpBc6/MatfmAg2rZ6xzSCpm1o=";
  };
in
{
  inherit date rev src;
}
